### ISSUE TITLE
Beginner: not sure why it is not running

### ISSUE THREAD

**Issue by achkeir** [Waultics/coinmarketcap-history#10]
hello,

when i am running the code, i am getting the following error:

Traceback (most recent call last):
  File "C:\Users\shouks\MyPythonScripts\coinmarketcap_usd_history.py", line 11, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

any suggestions ?>

**Comment by ls5014** [comment]
Seems like the package isn't installed on your system, but it's fairly straightforward to do.
     1. Open a terminal window on your system, could be found by typing 'cmd' in the Start Menu for Windows.
     2. Run "pip install urllib2"
Should work now, do this for all other packages in the future if you run into the same error message!

**Comment by nkzhengwt** [comment]
Maybe it is because you are in python 3 and there is not urllib2 in python 3.

**Comment by SrTobi** [comment]
I had the same error and I simply changed the first line to
```
#!/usr/bin/python2.7
```
I'm no python expert, so I don't know if @jhogan4288 wants this so I won't open a PR.

**Note**: [This post](https://stackoverflow.com/a/34475081/1393971) states that one should not use liburl2 in python3 because of security concerns.

**Comment by escontra** [comment]
Hi @achkeir, as @ls5014 mentioned, this error is caused by the python interpreter's inability to locate the `urllib2` module in your path. To fix this, simply open up your command prompt and run:

```shell
$ pip install urllib2
```
