### ISSUE TITLE
Code doesn't handle new header that contains *

### ISSUE THREAD

**Issue by CryptoIR** [Waultics/coinmarketcap-history#12]
Failed to parse coinmarketcap new header (open*, close**)

**Comment by CryptoIR** [comment]
head = re.search(r'<thead>(.*)</thead>', html, re.DOTALL).group(1)
-  header = re.findall(r'<th .*>([\w ]+)</th>', head)
+  header = re.findall(r'<th .*>([\w /*]+)</th>', head)
   header.append('Average (High + Low / 2)')
+  header = [s.replace('*', '') for s in header]

**Comment by CryptoIR** [comment]
<img width="605" alt="screen shot 2018-05-25 at 10 35 58" src="https://user-images.githubusercontent.com/37340769/40532241-7ddfc4fa-6007-11e8-9cfa-bd86df3ad9ec.png">

**Comment by CryptoIR** [comment]
@jhogan4288 - can you commit this fix?

**Comment by jhogan4288** [comment]
Can you submit it as a PR?

**Comment by nazariyv** [comment]
I will do it. I actually need this to work today.

**Comment by CryptoIR** [comment]
Thanks
