### ISSUE TITLE
Querying a series of coins

### ISSUE THREAD

**Issue by jbross45** [Waultics/coinmarketcap-history#14]
Hi,

Fantastic job on the script! I was wondering if there would be a way to input (or hardcode into the script) a series of coins, say 50-100. The output would then be the entire historical prices with the ticker or coin name as a new column.

Example of an ideal output (replace |'s with commas for the .csv file):

Ticker | Date | Open | High | Low | Close | Volume | MarketCap
-- | -- | -- | -- | -- | -- | -- | --
BTC | 05/29/18 | 7,129.460000 | 7,526.420000 | 7,090.680000 | 7,472.590000 | 5,662,660,000 | 121,636,000,000
BTC | 05/28/18 | 7,371.310000 | 7,419.050000 | 7,100.890000 | 7,135.990000 | 5,040,600,000 | 125,748,000,000
BTC | 05/27/18 | 7,362.080000 | 7,381.740000 | 7,270.960000 | 7,368.220000 | 4,056,520,000 | 125,575,000,000

ETH | 05/29/18 | 516.150000 | 572.260000 | 516.150000 | 565.390000 | 2,330,820,000 | 51,474,400,000
ETH | 05/28/18 | 573.040000 | 576.050000 | 512.550000 | 516.040000 | 2,356,900,000 | 57,136,700,000
ETH | 05/27/18 | 588.520000 | 590.330000 | 562.870000 | 572.670000 | 1,788,790,000 | 58,667,600,000

XRP | 05/29/18 | 0.556084 | 0.610749 | 0.551635 | 0.601241 | 380,744,000 | 21,792,900,000
XRP | 05/28/18 | 0.608368 | 0.609781 | 0.552299 | 0.552299 | 327,903,000 | 23,841,900,000
XRP | 05/27/18 | 0.612040 | 0.612884 | 0.603328 | 0.607881 | 186,963,000 | 23,985,800,000

Would something like this be possible given the current infrastructure of the coinmarketcap tables?

Best,

Julian

**Comment by jhogan4288** [comment]
This seems fairly straightforward, but I'm not actively maintaining the project at this point.  But I welcome you or anyone else to submit a PR!

**Comment by escontra** [comment]
Hi @jbross45, this functionality is being tested and a similar feature is due to be released in the next update. Monitor the repository for upcoming changes :smile:
