### ISSUE TITLE
Using the dataframe option in Python

### ISSUE THREAD

**Issue by lawlessz** [Waultics/coinmarketcap-history#15]
It seems like there are a series of changes and updates required to get this to work in python 3. Has anyone been able to upgrade the code to get it to make a dataframe? I have had a lot of trouble and it would be great if someone could explain this or show how it works.

**Comment by jhogan4288** [comment]
Not sure; I'm not actively maintaining it any longer.  Sorry!

**Comment by escontra** [comment]
Hi @lawlessz, integration with python 3 is in the works and will be rolled out in the next update. Monitor the repository for upcoming changes :)
