### ISSUE TITLE
What is the exact time of the data ?

### ISSUE THREAD

**Issue by Kinzowa** [Waultics/coinmarketcap-history#18]
Hello, first of all thank you for this library. I playing with CMC data and I was wondering what is the exact timestamp for the data in table at `https://coinmarketcap.com/currencies/<coin>/historical-data/`, do you have an idea ? 

From what I see data granularity is 15 minutes on the 7d chart but none of the value for Market Cap matches the ones in the table. The closest one is at 01:00 UTC+1 but I would like to be sure, if you have insight on this one I'll appreciate. Thanks again.

**Comment by synchronizing** [comment]
I can't answer about the specific link above, but I can tell you that with `cmc` you do have a time column that is functional and correct. `cmc` retrieves data differently than from the link above.
