### ISSUE TITLE
Header mix up

### ISSUE THREAD

**Issue by robrollback** [Waultics/coinmarketcap-history#20]
Hi,

When testing your command:

coinmarketcap bitcoin,ripple,ethereum 2017-01-01 2017-12-31 --async

I noticed the the coin headers and incorrectly assigned : Bitcoin and ripple should be switched

[bitcoin_history.txt](https://github.com/Alescontrela/coinmarketcap-history/files/2303146/bitcoin_history.txt)

**Comment by escontra** [comment]
Hi @robrollback ,

I can't recreate the issue you posted. The same command you tried provides the following output: 

`coinmarketcap bitcoin,ripple,ethereum 2017-01-01 2017-12-31 --async >> output.txt`

[output.txt](https://github.com/Alescontrela/coinmarketcap-history/files/2520191/output.txt)

If possible, could you supply additional examples of incorrect output. Thanks

**Comment by escontra** [comment]
Closing this as issue could not be recreated
