### ISSUE TITLE
After saved history as 'bitcoin_history.csv' then can't read_csv

### ISSUE THREAD

**Issue by CyberFork** [Waultics/coinmarketcap-history#28]
```python
import pandas as pd
pd.read_csv(r'..\bitcoin_history.csv')
```
```
error:UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by synchronizing** [comment]
> import pandas as pd
> pd.read_csv(r'..\bitcoin_history.csv')
> 
> error:UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Doesn't seem to be related to `coinmarketcap-history` repo, but to answer your question, you can't use raw strings in `pd.read_csv`. Simply remove the `r` in the `r'..\bitcoin_history.csv'`.

**Comment by synchronizing** [comment]
Could you paste/uplouad the output of `bitcoin_history.csv` file in here? Seems like the file is corrupted.

**Comment by synchronizing** [comment]
Closing due to lack of reply.
