### ISSUE TITLE
local variable 'html' referenced before assignment

### ISSUE THREAD

**Issue by gg4u** [Waultics/coinmarketcap-history#9]
Traceback (most recent call last):
  File "coinmarketcap_usd_history.py", line 180, in <module>
    df = main()
  File "coinmarketcap_usd_history.py", line 168, in main
    html = download_data(currency, start_date, end_date)
  File "coinmarketcap_usd_history.py", line 91, in download_data
    return html
UnboundLocalError: local variable 'html' referenced before assignment

**Comment by nazariyv** [comment]
I experienced this when I had no Internet connection

**Comment by nazariyv** [comment]
Think this should be closed.

**Comment by jhogan4288** [comment]
That's helpful context. It could benefit from better error handling, though. I'll leave it open in case someone wants to submit a PR.

**Comment by nazariyv** [comment]
I'll do it sometime next week.

**Comment by escontra** [comment]
HI @gg4u, this issue should no longer exist in 2.0.1. Please reach out if you continue to experience this error.
